# Generated by Django 5.0.4 on 2024-04-29 09:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tag",
            old_name="tag",
            new_name="name",
        ),
    ]
