# Generated by Django 5.0.4 on 2024-04-29 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                help_text="role of the user",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="role_user",
                to="accounts.role",
            ),
        ),
    ]
